/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   dialog-spinner-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {DialogSpinnerMixin};

declare function DialogSpinnerMixin<T extends new (...args: any[]) => {}>(base: T): T & DialogSpinnerMixinConstructor;

interface DialogSpinnerMixinConstructor {
  new(...args: any[]): DialogSpinnerMixin;
}

export {DialogSpinnerMixinConstructor};

interface DialogSpinnerMixin {
  keepDialogOpen: boolean|null|undefined;
  showSpinner: boolean|null|undefined;
  spinnerText: string|null|undefined;
  _confirmBtClicked(): void;
  startSpinner(): void;
  stopSpinner(): void;
}
