/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   dynamic-dialog-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {DynamicDialogMixin};

declare function DynamicDialogMixin<T extends new (...args: any[]) => {}>(base: T): T & DynamicDialogMixinConstructor;

interface DynamicDialogMixinConstructor {
  new(...args: any[]): DynamicDialogMixin;
}

export {DynamicDialogMixinConstructor};

interface DynamicDialogMixin {
  createDialog(title: any, size: any, okBtnText: any, cancelBtnText: any, closeCallback: any, content: any, removePadding: any, theme: any): any;
  createDynamicDialog(config: any): any;
  _validateParams(config: any): any;
  _applyDefaultDialogConfig(dialog: any): void;
  removeDialog(dialogElement: any): void;
}
